# Generated by Django 2.0.8 on 2018-08-22 02:32

import chisholm.blocks
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realestate', '0015_auto_20180822_0232'),
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailimages', '0021_image_file_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('canonical', models.URLField(blank=True, default='')),
                ('title_tag', models.CharField(blank=True, default='', max_length=255)),
                ('structured_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, help_text='json-ld Structured Data')),
                ('meta_title', models.CharField(blank=True, default='', max_length=255)),
                ('meta_description', models.TextField(blank=True, default='')),
                ('meta_keywords', models.TextField(blank=True, default='')),
                ('og_title', models.CharField(blank=True, default='', max_length=255)),
                ('og_type', models.CharField(blank=True, default='', max_length=50)),
                ('og_url', models.URLField(blank=True, default='')),
                ('og_img', models.URLField(blank=True, default='')),
                ('og_description', models.TextField(blank=True, default='')),
                ('twitter_card', models.CharField(blank=True, default='', help_text='Type of Twitter card', max_length=50)),
                ('twitter_site', models.CharField(blank=True, default='', help_text='@name of publisher', max_length=50)),
                ('twitter_title', models.CharField(blank=True, default='', max_length=255)),
                ('twitter_description', models.CharField(blank=True, default='', max_length=200)),
                ('twitter_creator', models.CharField(blank=True, default='', help_text='@name of author', max_length=50)),
                ('twitter_image', models.CharField(blank=True, default='', help_text='Images must be at least 120x120px', max_length=255)),
                ('template_override', models.CharField(blank=True, default='', help_text='Load this specific page template', max_length=255)),
                ('tagline', models.CharField(max_length=255)),
                ('cta_text', models.CharField(help_text='Call-to-Action button text', max_length=50)),
                ('content_sections', wagtail.core.fields.StreamField([('newsletter_signup', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(default='be the first to know')), ('subheading', wagtail.core.blocks.CharBlock(required=False))])), ('why_choose_us', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(default='why choose us?')), ('subheading', wagtail.core.blocks.CharBlock(required=False)), ('sections', wagtail.core.blocks.StreamBlock([('links', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('icon', wagtail.images.blocks.ImageChooserBlock()), ('image_location', wagtail.core.blocks.ChoiceBlock(choices=[('l', 'Left'), ('r', 'Right')])), ('links', wagtail.core.blocks.ListBlock(wagtail.core.blocks.PageChooserBlock(label='Links'))), ('image_overlay_text', wagtail.core.blocks.CharBlock(required=False))])), ('offices', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('icon', wagtail.images.blocks.ImageChooserBlock()), ('image_location', wagtail.core.blocks.ChoiceBlock(choices=[('l', 'Left'), ('r', 'Right')])), ('offices', wagtail.core.blocks.PageChooserBlock(target_model=['offices.OfficePage']))]))])), ('cta_text', wagtail.core.blocks.CharBlock(required=False)), ('cta_link', wagtail.core.blocks.PageChooserBlock(required=False))])), ('twin_panel', wagtail.core.blocks.StructBlock([('split', wagtail.core.blocks.ChoiceBlock(choices=[('50-50', '50\\% - 50\\%'), ('25-75', '25\\% - 75\\%'), ('75-25', '75\\% - 25\\%'), ('33-66', '1/3 - 2/3'), ('66-33', '2/3 - 1/3')])), ('panels', wagtail.core.blocks.StreamBlock([('latest_posts', wagtail.core.blocks.StructBlock([('number_of_articles', wagtail.core.blocks.IntegerBlock(default=3)), ('see_all_text', wagtail.core.blocks.CharBlock(help_text='Button text for "See all"', required=False)), ('see_all_link', wagtail.core.blocks.PageChooserBlock())])), ('find_it_fast', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(default='find it fast')), ('links', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('page', wagtail.core.blocks.PageChooserBlock()), ('tagline', wagtail.core.blocks.CharBlock(required=False))])))])), ('image_link', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('link', wagtail.core.blocks.PageChooserBlock())])), ('testimonials', wagtail.core.blocks.StructBlock([('testimonials', wagtail.core.blocks.ListBlock(wagtail.snippets.blocks.SnippetChooserBlock(target_model='testimonials.Testimonial')))])), ('offices', chisholm.blocks.OurOfficesBlock()), ('latest_properties', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(default='Latest Properties')), ('property_type', wagtail.core.blocks.ChoiceBlock(choices=[])), ('limit', wagtail.core.blocks.IntegerBlock(default=3))])), ('call_to_action', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('link', wagtail.core.blocks.PageChooserBlock()), ('secondary_link', wagtail.core.blocks.PageChooserBlock(help_text="Will show 2 CTA's side by side", required=False))]))], max_num=2))]))])),
                ('cta_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='HomePageFeaturedListings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='realestate.PropertyListing')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_listings', to='chisholm.HomePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePageHeroGalleryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_gallery', to='chisholm.HomePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
