# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-15 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0002_officepage_source_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeindexpage',
            name='template_override',
            field=models.CharField(blank=True, default='', help_text='Load this specific page template', max_length=255),
        ),
        migrations.AddField(
            model_name='officepage',
            name='template_override',
            field=models.CharField(blank=True, default='', help_text='Load this specific page template', max_length=255),
        ),
    ]
