# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-02 03:14
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('suburb', models.CharField(db_index=True, max_length=100)),
                ('postcode', models.CharField(max_length=4)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('state', models.CharField(choices=[('nsw', 'New South Wales'), ('vic', 'Victoria'), ('qld', 'Queensland'), ('tas', 'Tasmania'), ('sa', 'South Australia'), ('nt', 'Northern Territory'), ('act', 'Australian Capital Territory'), ('wa', 'Western Australia')], db_index=True, max_length=3)),
                ('school_level', models.CharField(blank=True, default='', max_length=50)),
                ('school_type', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
    ]
