# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-02 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='unique_id',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(blank=True, choices=[('private', 'Private'), ('public', 'Public')], default='', max_length=50),
        ),
    ]
