# Generated by Django 2.0.5 on 2018-05-24 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentBoxSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, default='', max_length=255)),
                ('client_id', models.CharField(blank=True, default='', max_length=255)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgentBoxUpdateMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated_listings', models.DateTimeField(default=None, null=True)),
                ('last_updated_offices', models.DateTimeField(default=None, null=True)),
                ('last_updated_staff', models.DateTimeField(default=None, null=True)),
                ('last_updated_lookups', models.DateTimeField(default=None, null=True)),
            ],
        ),
    ]
