# Generated by Django 2.0.5 on 2018-05-24 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentboxsettings',
            name='staff_webdisplay',
            field=models.CharField(blank=True, default='', help_text='webDisplay type from AgentBox to expect for public profiles. If not supplied will use all', max_length=50),
        ),
    ]
