# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-08 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import realestate.listings.models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertylisting',
            name='holiday',
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='bedrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='parking',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspection_end_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='End'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspection_time',
            field=models.DateTimeField(verbose_name='Start'),
        ),
        migrations.AlterField(
            model_name='propertycategory',
            name='name',
            field=models.CharField(choices=[('residential', [('House', 'House'), ('Unit', 'Unit'), ('Townhouse', 'Townhouse'), ('Villa', 'Villa'), ('Apartment', 'Apartment'), ('Flat', 'Flat'), ('Studio', 'Studio'), ('Warehouse', 'Warehouse'), ('DuplexSemi-detached', 'DuplexSemi-detached'), ('Alpine', 'Alpine'), ('AcreageSemi-rural', 'AcreageSemi-rural'), ('Retirement', 'Retirement'), ('BlockOfUnits', 'BlockOfUnits'), ('Terrace', 'Terrace'), ('ServicedApartment', 'ServicedApartment'), ('Other', 'Other')]), ('commercial', [('Commercial Farming', 'Commercial Farming'), ('Land/Development', 'Land/Development'), ('Hotel/Leisure', 'Hotel/Leisure'), ('Industrial/Warehouse', 'Industrial/Warehouse'), ('Medical/Consulting', 'Medical/Consulting'), ('Offices', 'Offices'), ('Retail', 'Retail'), ('Showrooms/Bulky Goods', 'Showrooms/Bulky Goods'), ('Other', 'Other')]), ('holidayRental', [('Alpine', 'Alpine'), ('Unit', 'Unit'), ('ServicedApartment', 'ServicedApartment'), ('House', 'House'), ('Terrace', 'Terrace'), ('Flat', 'Flat'), ('Studio', 'Studio'), ('Villa', 'Villa'), ('Townhouse', 'Townhouse'), ('Apartment', 'Apartment'), ('DuplexSemi', 'DuplexSemi'), ('Retreat', 'Retreat'), ('BackpackerHostel', 'BackpackerHostel'), ('Campground', 'Campground'), ('CaravanHolidayPark', 'CaravanHolidayPark'), ('FarmStay', 'FarmStay'), ('HouseBoat', 'HouseBoat'), ('Hotel', 'Hotel'), ('Motel', 'Motel'), ('Lodge', 'Lodge'), ('ExecutiveRental', 'ExecutiveRental'), ('BedAndBreakfast', 'BedAndBreakfast'), ('Resort', 'Resort'), ('SelfContainedCottage', 'SelfContainedCottage'), ('Other', 'Other')]), ('rural', [('Cropping', 'Cropping'), ('Dairy', 'Dairy'), ('Farmlet', 'Farmlet'), ('Horticulture', 'Horticulture'), ('Livestock', 'Livestock'), ('Viticulture', 'Viticulture'), ('MixedFarming', 'MixedFarming'), ('Lifestyle', 'Lifestyle'), ('Other', 'Other')])], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='_return',
            field=models.DecimalField(decimal_places=2, default=None, help_text='% return annually', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='address_suburb_display',
            field=realestate.listings.models.REAXMLBoolean(default=True, verbose_name='Show Suburb'),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='authority',
            field=models.CharField(choices=[('auction', 'Auction'), ('exclusive', 'Exclusive'), ('multilist', 'Multilist'), ('conjunctional', 'Conjunctional'), ('open', 'Open'), ('sale', 'Sale'), ('setsale', 'Setsale')], default='sale', max_length=15),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='commercialAuthority_value',
            field=models.CharField(choices=[('auction', 'Auction'), ('tender', 'Tender'), ('eoi', 'Eoi'), ('sale', 'Sale'), ('forsale', 'Forsale'), ('offers', 'Offers')], default='sale', max_length=10, verbose_name='Commercial Authority'),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='commercialRent',
            field=models.IntegerField(default=0, help_text='Annually'),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='exclusivity_value',
            field=models.CharField(choices=[('exclusive', 'Exclusive'), ('open', 'Open')], default='exclusive', max_length=10, verbose_name='Exclusivity'),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='isHomeLandPackage',
            field=realestate.listings.models.REAXMLBoolean(default=False, verbose_name='Home & Land Package'),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='newConstruction',
            field=realestate.listings.models.REAXMLBoolean(default=False, verbose_name='New Construction'),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='outgoings',
            field=models.IntegerField(default=0, help_text='Annual outgoings'),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='price',
            field=models.IntegerField(blank=True, db_index=True, default=0, help_text='The price (number), used for searching', null=True),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='priceView',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Price Display text'),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='salebySetDate',
            field=realestate.listings.models.REAXMLDateTimeField(blank=True, default=None, null=True, verbose_name='Sale by set date'),
        ),
    ]
