# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-12 03:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0002_auto_20180108_0342'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingEnquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('email_address', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(blank=True, default='', max_length=25)),
                ('message', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.PropertyListing')),
            ],
        ),
    ]
