# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-26 08:25
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0004_listingsearchpage_searchpagefeaturedlisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingsearchpage',
            name='search_params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, help_text='Form parameters to pass the backend. DO NOT EDIT without prior knowledge'),
        ),
    ]
