# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-28 00:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0005_auto_20180126_0825'),
        ('realestate', '0005_auto_20180122_0102'),
    ]

    operations = [
    ]
