# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-28 00:27
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0006_merge_20180128_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylisting',
            name='_return',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='% return annually', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='commercialAuthority_value',
            field=models.CharField(blank=True, choices=[('auction', 'Auction'), ('tender', 'Tender'), ('eoi', 'Eoi'), ('sale', 'Sale'), ('forsale', 'Forsale'), ('offers', 'Offers')], default='sale', max_length=10, null=True, verbose_name='Commercial Authority'),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='exclusivity_value',
            field=models.CharField(blank=True, choices=[('exclusive', 'Exclusive'), ('open', 'Open')], default='exclusive', max_length=10, null=True, verbose_name='Exclusivity'),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='extraFields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='rent',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='rent_period',
            field=models.CharField(blank=True, choices=[('week', 'Week'), ('weekly', 'Weekly'), ('month', 'Month'), ('monthly', 'Monthly')], default='week', max_length=10, null=True),
        ),
    ]
