# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-01 23:18
from __future__ import unicode_literals

from django.db import migrations


def create_default_searchpages(apps, schema_editor):
    from wagtail.core.models import Site
    from realestate.listings.models import ListingSearchPage
    site_root = Site.objects.latest('pk').root_page

    forsale = ListingSearchPage(
        title="Buying",
        slug="buying",
        search_params={
            "property_class": "residential",
            "listing_type": "sale",
            "status": "current"
        }
    )

    forent = ListingSearchPage(
        title="Renting",
        slug="renting",
        search_params={
            "property_class": "residential",
            "listing_type": "lease",
            "status": "current"
        }
    )

    comm = ListingSearchPage(
        title="Commercial",
        slug="commercial",
        search_params={
            "property_class": "commercial",
            "status": "current"
        }
    )

    site_root.add_child(instance=forsale)
    site_root.add_child(instance=forent)
    site_root.add_child(instance=comm)


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0007_auto_20180128_0027'),
    ]

    operations = [
        # migrations.RunPython(create_default_searchpages)
    ]
