# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-01 23:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0008_auto_20180201_2318'),
        ('realestate', '0008_merge_20180130_0531'),
    ]

    operations = [
    ]
