# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-06 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0010_merge_20180205_0811'),
        ('realestate', '0009_merge_20180201_2344'),
    ]

    operations = [
    ]
