# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-19 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0011_merge_20180206_2010'),
        ('realestate', '0011_listingsearchpage_structured_data'),
    ]

    operations = [
    ]
