# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-05 22:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0012_auto_20180305_0011'),
        ('realestate', '0012_merge_20180219_0316'),
    ]

    operations = [
    ]
