# Generated by Django 2.0.3 on 2018-03-15 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0013_merge_20180305_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingenquiry',
            name='listing',
        ),
        migrations.DeleteModel(
            name='ListingEnquiry',
        ),
    ]
