# Generated by Django 2.0.8 on 2018-08-22 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0014_auto_20180315_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listingfloorplan',
            options={},
        ),
        migrations.AlterModelOptions(
            name='listingimage',
            options={},
        ),
        migrations.AddField(
            model_name='listingfloorplan',
            name='external_modtime',
            field=models.DateTimeField(blank=True, default=None, help_text='Modified Date from External System', null=True),
        ),
        migrations.AddField(
            model_name='listingfloorplan',
            name='modtime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='external_modtime',
            field=models.DateTimeField(blank=True, default=None, help_text='Modified Date from External System', null=True),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='modtime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
