"""Various enums for REAXML processing."""

from __future__ import unicode_literals

# Top level of each property in the REAXML
PROPERTYLIST_CLASSES = {
    'CommercialListing': 'commercial',
    'LandListing': 'land',
    'RentalListing': 'rental',
    'HolidayRentalListing': 'holidayRental',
    'ResidentialSaleListing': 'residential',
    'RuralListing': 'rural',
}

PROPERTY_CLASS_COMMERCIAL = 'commercial'
PROPERTY_CLASS_LAND = 'land'
PROPERTY_CLASS_RENTAL = 'rental'
PROPERTY_CLASS_RESIDENTIAL = 'residential'
PROPERTY_CLASS_HOLIDAY = 'holidayRental'
PROPERTY_CLASS_RURAL = 'rural'

PROPERTY_CLASS_CHOICES = (
    (PROPERTY_CLASS_RESIDENTIAL, PROPERTY_CLASS_RESIDENTIAL.title()),
    (PROPERTY_CLASS_COMMERCIAL, PROPERTY_CLASS_COMMERCIAL.title()),
    (PROPERTY_CLASS_LAND, PROPERTY_CLASS_LAND.title()),
    (PROPERTY_CLASS_HOLIDAY, 'Holiday'),
    (PROPERTY_CLASS_RURAL, PROPERTY_CLASS_RURAL.title()),
)

DEFAULT_PROPERTY_CLASS = PROPERTY_CLASS_RESIDENTIAL

# States
STATE_ACT = 'ACT'
STATE_NSW = 'NSW'
STATE_VIC = 'VIC'
STATE_SA = 'SA'
STATE_QLD = 'QLD'
STATE_WA = 'WA'
STATE_NT = 'NT'
STATE_TAS = 'TAS'

STATE_CHOICES = [
    (STATE_ACT, 'Australian Capitol Territory'),
    (STATE_NSW, 'New South Wales'),
    (STATE_VIC, 'Victoria'),
    (STATE_SA, 'South Australia'),
    (STATE_QLD, 'Queensland'),
    (STATE_WA, 'Western Australia'),
    (STATE_NT, 'Northern Territory'),
    (STATE_TAS, 'Tasmania')
]

# Property Status
STATUS_CURRENT = 'current'
STATUS_WITHDRAWN = 'withdrawn'
STATUS_OFFMARKET = 'offmarket'
STATUS_DELETED = 'deleted'
STATUS_LEASED = 'leased'
STATUS_SOLD = 'sold'
STATUS_PREMARKET = 'premarket'

DEFAULT_STATUS = STATUS_CURRENT

STATUS_CHOICES = [
    (STATUS_CURRENT, STATUS_CURRENT.title()),
    (STATUS_PREMARKET, 'Pre-Market / Off market Sale'),
    (STATUS_WITHDRAWN, STATUS_WITHDRAWN.title()),
    (STATUS_OFFMARKET, 'Off market: Not for Sale/Lease'),
    (STATUS_DELETED, STATUS_DELETED.title()),
    (STATUS_LEASED, STATUS_LEASED.title()),
    (STATUS_SOLD, STATUS_SOLD.title()),
]

AUTHORITY_AUCTION = 'auction'
AUTHORITY_EXCLUSIVE = 'exclusive'
AUTHORITY_MULTILIST = 'multilist'
AUTHORITY_CONJUNCTIONAL = 'conjunctional'
AUTHORITY_OPEN = 'open'
AUTHORITY_SALE = 'sale'
AUTHORITY_SETSALE = 'setsale'

AUTHORITY_CHOICES = [
    (AUTHORITY_AUCTION, AUTHORITY_AUCTION.title()),
    (AUTHORITY_EXCLUSIVE, AUTHORITY_EXCLUSIVE.title()),
    (AUTHORITY_MULTILIST, AUTHORITY_MULTILIST.title()),
    (AUTHORITY_CONJUNCTIONAL, AUTHORITY_CONJUNCTIONAL.title()),
    (AUTHORITY_OPEN, AUTHORITY_OPEN.title()),
    (AUTHORITY_SALE, AUTHORITY_SALE.title()),
    (AUTHORITY_SETSALE, AUTHORITY_SETSALE.title()),
]

DEFAULT_AUTHORITY = AUTHORITY_SALE

LISTING_TYPE_SALE = 'sale'
LISTING_TYPE_LEASE = 'lease'
LISTING_TYPE_BOTH = 'both'

LISTING_TYPE_CHOICES = [
    (LISTING_TYPE_SALE, LISTING_TYPE_SALE.title()),
    (LISTING_TYPE_LEASE, LISTING_TYPE_LEASE.title()),
    (LISTING_TYPE_BOTH, LISTING_TYPE_BOTH.title())
]

DEFAULT_LISTING_TYPE = LISTING_TYPE_SALE

PHONE_TYPE_BUSINESS = 'BH'
PHONE_TYPE_AFTER = 'AH'
PHONE_TYPE_MOBILE = 'mobile'

PHONE_TYPE_CHOICES = [
    (PHONE_TYPE_BUSINESS, "Business Hours"),
    (PHONE_TYPE_AFTER, "After Hours"),
    (PHONE_TYPE_MOBILE, "Mobile")
]
DEFAULT_PHONE_TYPE = PHONE_TYPE_BUSINESS

RENT_PERIOD_WEEK = 'week'
RENT_PERIOD_WEEKLY = 'weekly'
RENT_PERIOD_MONTH = 'month'
RENT_PERIOD_MONTHLY = 'monthly'

RENT_PERIOD_CHOICES = [
    (RENT_PERIOD_WEEK, RENT_PERIOD_WEEK.title()),
    (RENT_PERIOD_WEEKLY, RENT_PERIOD_WEEKLY.title()),
    (RENT_PERIOD_MONTH, RENT_PERIOD_MONTH.title()),
    (RENT_PERIOD_MONTHLY, RENT_PERIOD_MONTHLY.title())
]
DEFAULT_RENT_PERIOD = RENT_PERIOD_WEEK

OBJECT_TYPE_IMAGE = 'img'
OBJECT_TYPE_FLOORPLAN = 'flooplan'
OBJECT_TYPE_DOCUMENT = 'document'
OBJECT_TYPE_ATTACHMENT = 'attachment'

OBJECT_TYPE_CHOICES = [
    (OBJECT_TYPE_IMAGE, OBJECT_TYPE_IMAGE.title()),
    (OBJECT_TYPE_FLOORPLAN, OBJECT_TYPE_FLOORPLAN.title()),
    (OBJECT_TYPE_DOCUMENT, OBJECT_TYPE_DOCUMENT.title()),
    (OBJECT_TYPE_ATTACHMENT, OBJECT_TYPE_ATTACHMENT.title())
]

CATEGORY_HOUSE = 'House'
CATEGORY_UNIT = 'Unit'
CATEGORY_TOWNHOUSE = 'Townhouse'
CATEGORY_VILLA = 'Villa'
CATEGORY_APARTMENT = 'Apartment'
CATEGORY_FLAT = 'Flat'
CATEGORY_STUDIO = 'Studio'
CATEGORY_WAREHOUSE = 'Warehouse'
CATEGORY_DUPLEX = 'DuplexSemi-detached'
CATEGORY_ALPINE = 'Alpine'
CATEGORY_ACREAGE = 'AcreageSemi-rural'
CATEGORY_RETIREMENT = 'Retirement'
CATEGORY_BLOCK = 'BlockOfUnits'
CATEGORY_TERRACE = 'Terrace'
CATEGORY_SERVICED = 'ServicedApartment'
CATEGORY_OTHER = 'Other'

RES_CATEGORY_CHOICES = [
    (CATEGORY_HOUSE, CATEGORY_HOUSE),
    (CATEGORY_UNIT, CATEGORY_UNIT),
    (CATEGORY_TOWNHOUSE, CATEGORY_TOWNHOUSE),
    (CATEGORY_VILLA, CATEGORY_VILLA),
    (CATEGORY_APARTMENT, CATEGORY_APARTMENT),
    (CATEGORY_FLAT, CATEGORY_FLAT),
    (CATEGORY_STUDIO, CATEGORY_STUDIO),
    (CATEGORY_WAREHOUSE, CATEGORY_WAREHOUSE),
    (CATEGORY_DUPLEX, CATEGORY_DUPLEX),
    (CATEGORY_ALPINE, CATEGORY_ALPINE),
    (CATEGORY_ACREAGE, CATEGORY_ACREAGE),
    (CATEGORY_RETIREMENT, CATEGORY_RETIREMENT),
    (CATEGORY_BLOCK, CATEGORY_BLOCK),
    (CATEGORY_TERRACE, CATEGORY_TERRACE),
    (CATEGORY_SERVICED, CATEGORY_SERVICED),
    (CATEGORY_OTHER, CATEGORY_OTHER)
]

HOLIDAYCATEGORY_ALPINE = 'Alpine'
HOLIDAYCATEGORY_UNIT = 'Unit'
HOLIDAYCATEGORY_SERVICED = 'ServicedApartment'
HOLIDAYCATEGORY_HOUSE = 'House'
HOLIDAYCATEGORY_TERRACE = 'Terrace'
HOLIDAYCATEGORY_FLAT = 'Flat'
HOLIDAYCATEGORY_STUDIO = 'Studio'
HOLIDAYCATEGORY_VILLA = 'Villa'
HOLIDAYCATEGORY_TOWN = 'Townhouse'
HOLIDAYCATEGORY_APARTMENT = 'Apartment'
HOLIDAYCATEGORY_DUPLEX = 'DuplexSemi'
HOLIDAYCATEGORY_RETREAT = 'Retreat'
HOLIDAYCATEGORY_HOSTEL = 'BackpackerHostel'
HOLIDAYCATEGORY_CAMP = 'Campground'
HOLIDAYCATEGORY_CARAVAN = 'CaravanHolidayPark'
HOLIDAYCATEGORY_FARM = 'FarmStay'
HOLIDAYCATEGORY_BOAT = 'HouseBoat'
HOLIDAYCATEGORY_HOTEL = 'Hotel'
HOLIDAYCATEGORY_MOTEL = 'Motel'
HOLIDAYCATEGORY_LODGE = 'Lodge'
HOLIDAYCATEGORY_EXEC = 'ExecutiveRental'
HOLIDAYCATEGORY_BED = 'BedAndBreakfast'
HOLIDAYCATEGORY_RESORT = 'Resort'
HOLIDAYCATEGORY_COTTAGE = 'SelfContainedCottage'
HOLIDAYCATEGORY_OTHER = 'Other'

HOLIDAYCATEGORY_CHOICES = [
    (HOLIDAYCATEGORY_ALPINE, HOLIDAYCATEGORY_ALPINE),
    (HOLIDAYCATEGORY_UNIT, HOLIDAYCATEGORY_UNIT),
    (HOLIDAYCATEGORY_SERVICED, HOLIDAYCATEGORY_SERVICED),
    (HOLIDAYCATEGORY_HOUSE, HOLIDAYCATEGORY_HOUSE),
    (HOLIDAYCATEGORY_TERRACE, HOLIDAYCATEGORY_TERRACE),
    (HOLIDAYCATEGORY_FLAT, HOLIDAYCATEGORY_FLAT),
    (HOLIDAYCATEGORY_STUDIO, HOLIDAYCATEGORY_STUDIO),
    (HOLIDAYCATEGORY_VILLA, HOLIDAYCATEGORY_VILLA),
    (HOLIDAYCATEGORY_TOWN, HOLIDAYCATEGORY_TOWN),
    (HOLIDAYCATEGORY_APARTMENT, HOLIDAYCATEGORY_APARTMENT),
    (HOLIDAYCATEGORY_DUPLEX, HOLIDAYCATEGORY_DUPLEX),
    (HOLIDAYCATEGORY_RETREAT, HOLIDAYCATEGORY_RETREAT),
    (HOLIDAYCATEGORY_HOSTEL, HOLIDAYCATEGORY_HOSTEL),
    (HOLIDAYCATEGORY_CAMP, HOLIDAYCATEGORY_CAMP),
    (HOLIDAYCATEGORY_CARAVAN, HOLIDAYCATEGORY_CARAVAN),
    (HOLIDAYCATEGORY_FARM, HOLIDAYCATEGORY_FARM),
    (HOLIDAYCATEGORY_BOAT, HOLIDAYCATEGORY_BOAT),
    (HOLIDAYCATEGORY_HOTEL, HOLIDAYCATEGORY_HOTEL),
    (HOLIDAYCATEGORY_MOTEL, HOLIDAYCATEGORY_MOTEL),
    (HOLIDAYCATEGORY_LODGE, HOLIDAYCATEGORY_LODGE),
    (HOLIDAYCATEGORY_EXEC, HOLIDAYCATEGORY_EXEC),
    (HOLIDAYCATEGORY_BED, HOLIDAYCATEGORY_BED),
    (HOLIDAYCATEGORY_RESORT, HOLIDAYCATEGORY_RESORT),
    (HOLIDAYCATEGORY_COTTAGE, HOLIDAYCATEGORY_COTTAGE),
    (HOLIDAYCATEGORY_OTHER, HOLIDAYCATEGORY_OTHER)
]

RURAL_CATEGORY_CROPPING = 'Cropping'
RURAL_CATEGORY_DAIRY = 'Dairy'
RURAL_CATEGORY_FARMLET = 'Farmlet'
RURAL_CATEGORY_HORTICULTURE = 'Horticulture'
RURAL_CATEGORY_LIVESTOCK = 'Livestock'
RURAL_CATEGORY_VITI = 'Viticulture'
RURAL_CATEGORY_MIX = 'MixedFarming'
RURAL_CATEGORY_LIFESTYLE = 'Lifestyle'
RURAL_CATEGORY_OTHER = 'Other'

RURAL_CATEGORY_CHOICES = [
    (RURAL_CATEGORY_CROPPING, RURAL_CATEGORY_CROPPING),
    (RURAL_CATEGORY_DAIRY, RURAL_CATEGORY_DAIRY),
    (RURAL_CATEGORY_FARMLET, RURAL_CATEGORY_FARMLET),
    (RURAL_CATEGORY_HORTICULTURE, RURAL_CATEGORY_HORTICULTURE),
    (RURAL_CATEGORY_LIVESTOCK, RURAL_CATEGORY_LIVESTOCK),
    (RURAL_CATEGORY_VITI, RURAL_CATEGORY_VITI),
    (RURAL_CATEGORY_MIX, RURAL_CATEGORY_MIX),
    (RURAL_CATEGORY_LIFESTYLE, RURAL_CATEGORY_LIFESTYLE),
    (RURAL_CATEGORY_OTHER, RURAL_CATEGORY_OTHER)
]

COMMERCIAL_AUTHORITY_AUCTION = 'auction'
COMMERCIAL_AUTHORITY_TENDER = 'tender'
COMMERCIAL_AUTHORITY_EOI = 'eoi'
COMMERCIAL_AUTHORITY_SALE = 'sale'
COMMERCIAL_AUTHORITY_FORSALE = 'forsale'
COMMERCIAL_AUTHORITY_OFFERS = 'offers'

COMMERCIAL_AUTHORITY_CHOICES = [
    (COMMERCIAL_AUTHORITY_AUCTION, COMMERCIAL_AUTHORITY_AUCTION.title()),
    (COMMERCIAL_AUTHORITY_TENDER, COMMERCIAL_AUTHORITY_TENDER.title()),
    (COMMERCIAL_AUTHORITY_EOI, COMMERCIAL_AUTHORITY_EOI.title()),
    (COMMERCIAL_AUTHORITY_SALE, COMMERCIAL_AUTHORITY_SALE.title()),
    (COMMERCIAL_AUTHORITY_FORSALE, COMMERCIAL_AUTHORITY_FORSALE.title()),
    (COMMERCIAL_AUTHORITY_OFFERS, COMMERCIAL_AUTHORITY_OFFERS.title())
]
DEFAULT_COMMERCIAL_AUTHORITY = COMMERCIAL_AUTHORITY_SALE

COMMERCIAL_EXCLUSIVITY_EXCLUSIVE = 'exclusive'
COMMERCIAL_EXCLUSIVITY_OPEN = 'open'

COMMERCIAL_EXCLUSIVITY_CHOICES = [
    (COMMERCIAL_EXCLUSIVITY_EXCLUSIVE, COMMERCIAL_EXCLUSIVITY_EXCLUSIVE.title()),
    (COMMERCIAL_EXCLUSIVITY_OPEN, COMMERCIAL_EXCLUSIVITY_OPEN.title())
]

DEFAULT_COMMERCIAL_EXCLUSIVITY = COMMERCIAL_EXCLUSIVITY_EXCLUSIVE

TAX_UNKNOWN = 'unknown'
TAX_EXEMPT = 'exempt'
TAX_INCLUSIVE = 'inclusive'
TAX_EXCLUSIVE = 'exclusive'

TAX_CHOICES = [
    (TAX_UNKNOWN, TAX_UNKNOWN.title()),
    (TAX_EXEMPT, TAX_EXEMPT.title()),
    (TAX_INCLUSIVE, TAX_INCLUSIVE.title()),
    (TAX_EXCLUSIVE, TAX_EXCLUSIVE.title())
]

DEFAULT_TAX = TAX_UNKNOWN

TENANCY_UNKNOWN = 'unknown'
TENANCY_VACANT = 'vacant'
TENANCY_TENANTED = 'tenanted'

TENANCY_CHOICES = [
    (TENANCY_UNKNOWN, TENANCY_UNKNOWN.title()),
    (TENANCY_VACANT, TENANCY_VACANT.title()),
    (TENANCY_TENANTED, TENANCY_TENANTED.title())
]
DEFAULT_TENANCY = TENANCY_UNKNOWN

EXTENT_WHOLE = 'whole'
EXTEND_PART = 'part'

EXTENT_CHOICES = [
    (EXTENT_WHOLE, EXTENT_WHOLE.title()),
    (EXTEND_PART, EXTEND_PART.title())
]

COMMERCIALCATEGORY_FARMING = 'Commercial Farming'
COMMERCIALCATEGORY_LAND = 'Land/Development'
COMMERCIALCATEGORY_HOTEL = 'Hotel/Leisure'
COMMERCIALCATEGORY_INDUSTRIAL = 'Industrial/Warehouse'
COMMERCIALCATEGORY_MEDICAL = 'Medical/Consulting'
COMMERCIALCATEGORY_OFFICES = 'Offices'
COMMERCIALCATEGORY_RETAIL = 'Retail'
COMMERCIALCATEGORY_SHOWROOM = 'Showrooms/Bulky Goods'
COMMERCIALCATEGORY_OTHER = 'Other'

COMMERCIALCATEGORY_CHOICES = [
    (COMMERCIALCATEGORY_FARMING, COMMERCIALCATEGORY_FARMING),
    (COMMERCIALCATEGORY_LAND, COMMERCIALCATEGORY_LAND),
    (COMMERCIALCATEGORY_HOTEL, COMMERCIALCATEGORY_HOTEL),
    (COMMERCIALCATEGORY_INDUSTRIAL, COMMERCIALCATEGORY_INDUSTRIAL),
    (COMMERCIALCATEGORY_MEDICAL, COMMERCIALCATEGORY_MEDICAL),
    (COMMERCIALCATEGORY_OFFICES, COMMERCIALCATEGORY_OFFICES),
    (COMMERCIALCATEGORY_RETAIL, COMMERCIALCATEGORY_RETAIL),
    (COMMERCIALCATEGORY_SHOWROOM, COMMERCIALCATEGORY_SHOWROOM),
    (COMMERCIALCATEGORY_OTHER, COMMERCIALCATEGORY_OTHER)
]


CATEGORY_CHOICES = [
    (PROPERTY_CLASS_RESIDENTIAL, RES_CATEGORY_CHOICES),
    (PROPERTY_CLASS_COMMERCIAL, COMMERCIALCATEGORY_CHOICES),
    (PROPERTY_CLASS_HOLIDAY, HOLIDAYCATEGORY_CHOICES),
    (PROPERTY_CLASS_RURAL, RURAL_CATEGORY_CHOICES),
]

LINK_TYPE_EXTERNAL = 'external'
LINK_TYPE_VIDEO = 'video'
LINK_TYPE_TOUR = 'vtour'
LINK_TYPE_SOI = 'soi'
LINK_TYPE_MINIWEB = 'miniweb'
LINK_TYPE_360 = '360tour'

LINK_TYPE_CHOICES = [
    (LINK_TYPE_EXTERNAL, LINK_TYPE_EXTERNAL.title()),
    (LINK_TYPE_VIDEO, LINK_TYPE_VIDEO.title()),
    (LINK_TYPE_TOUR, LINK_TYPE_TOUR.title()),
    (LINK_TYPE_SOI, 'Statement of Information'),
    (LINK_TYPE_MINIWEB, LINK_TYPE_MINIWEB.title()),
    (LINK_TYPE_360, '360 Tour')
]

ERRORS_UNAUTHORIZED = 'XML User/Pass not authorized for this agentID'

ORDER_BY_PRICE_LOW = 'price,rent'
ORDER_BY_PRICE_HIGH = '-price,-rent'
ORDER_BY_CREATED_NEW = '-created'
ORDER_BY_CREATED = 'created'
ORDER_BY_UPDATED = '-updated'

ORDER_BY_CHOICES = [
    (ORDER_BY_CREATED_NEW, 'Newly Created'),
    (ORDER_BY_CREATED, 'Oldest'),
    (ORDER_BY_PRICE_LOW, 'Cheapest'),
    (ORDER_BY_PRICE_HIGH, 'Most Expensive'),
    (ORDER_BY_UPDATED, 'Last Updated')
]

DEFAULT_ORDER_BY = ORDER_BY_CREATED_NEW
