# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 04:22
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('wagtailcore', '0040_page_draft_title'),
        ('offices', '0004_auto_20180219_0302'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('canonical', models.URLField(blank=True, default='')),
                ('title_tag', models.CharField(blank=True, default='', max_length=255)),
                ('structured_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, help_text='json-ld Structured Data')),
                ('meta_title', models.CharField(blank=True, default='', max_length=255)),
                ('meta_description', models.TextField(blank=True, default='')),
                ('meta_keywords', models.TextField(blank=True, default='')),
                ('og_title', models.CharField(blank=True, default='', max_length=255)),
                ('og_type', models.CharField(blank=True, default='', max_length=50)),
                ('og_url', models.URLField(blank=True, default='')),
                ('og_img', models.URLField(blank=True, default='')),
                ('og_description', models.TextField(blank=True, default='')),
                ('twitter_card', models.CharField(blank=True, default='', help_text='Type of Twitter card', max_length=50)),
                ('twitter_site', models.CharField(blank=True, default='', help_text='@name of publisher', max_length=50)),
                ('twitter_title', models.CharField(blank=True, default='', max_length=255)),
                ('twitter_description', models.CharField(blank=True, default='', max_length=200)),
                ('twitter_creator', models.CharField(blank=True, default='', help_text='@name of author', max_length=50)),
                ('twitter_image', models.CharField(blank=True, default='', help_text='Images must be at least 120x120px', max_length=255)),
                ('template_override', models.CharField(blank=True, default='', help_text='Load this specific page template', max_length=255)),
                ('headline', wagtail.core.fields.RichTextField(help_text="Text across banner. Content marked as 'bold' will show pink")),
                ('sub_headline', models.CharField(blank=True, default='', help_text='Displayed under the banner image', max_length=255)),
                ('description', wagtail.core.fields.RichTextField(blank=True, default='', help_text='Displayed under the Sub Headline and Banner image')),
                ('testimonial_content', wagtail.core.fields.RichTextField(blank=True, default='')),
                ('testimonial_name', models.CharField(blank=True, default='', max_length=255)),
                ('testimonail_title', models.CharField(blank=True, default='', max_length=255)),
                ('footer_headline', models.CharField(blank=True, default='', help_text='Displayed under the current positions', max_length=255)),
                ('footer_content', wagtail.core.fields.RichTextField(blank=True, default='', help_text='Displayed under the Footer headline and Banner image')),
                ('footer_cta_text', models.CharField(blank=True, default='', max_length=50, verbose_name='Footer Call-to-Action')),
                ('banner_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('testimonial_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='CareerIndexPageGalleryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='careers.CareerIndexPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CareerPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('canonical', models.URLField(blank=True, default='')),
                ('title_tag', models.CharField(blank=True, default='', max_length=255)),
                ('structured_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, help_text='json-ld Structured Data')),
                ('meta_title', models.CharField(blank=True, default='', max_length=255)),
                ('meta_description', models.TextField(blank=True, default='')),
                ('meta_keywords', models.TextField(blank=True, default='')),
                ('og_title', models.CharField(blank=True, default='', max_length=255)),
                ('og_type', models.CharField(blank=True, default='', max_length=50)),
                ('og_url', models.URLField(blank=True, default='')),
                ('og_img', models.URLField(blank=True, default='')),
                ('og_description', models.TextField(blank=True, default='')),
                ('twitter_card', models.CharField(blank=True, default='', help_text='Type of Twitter card', max_length=50)),
                ('twitter_site', models.CharField(blank=True, default='', help_text='@name of publisher', max_length=50)),
                ('twitter_title', models.CharField(blank=True, default='', max_length=255)),
                ('twitter_description', models.CharField(blank=True, default='', max_length=200)),
                ('twitter_creator', models.CharField(blank=True, default='', help_text='@name of author', max_length=50)),
                ('twitter_image', models.CharField(blank=True, default='', help_text='Images must be at least 120x120px', max_length=255)),
                ('template_override', models.CharField(blank=True, default='', help_text='Load this specific page template', max_length=255)),
                ('date_posted', models.DateField(blank=True, default=None, help_text='Used for Ordering', null=True)),
                ('closing_date', models.DateField(blank=True, default=None, help_text='Position will stop displaying after this date', null=True)),
                ('job_name', models.CharField(help_text='Name of the Job Position', max_length=255)),
                ('job_type', models.CharField(choices=[('full', 'Full Time'), ('part', 'Part Time'), ('casual', 'Casual')], max_length=10)),
                ('description', wagtail.core.fields.RichTextField(blank=True, default='')),
                ('location', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offices.OfficePage')),
            ],
            options={
                'ordering': ['-date_posted'],
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='CareerPageCheckMarkItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=25)),
                ('text', models.CharField(blank=True, default='', max_length=255)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkmark_items', to='careers.CareerIndexPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
