# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-11 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentpage',
            name='source_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
