# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-15 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_auto_20180129_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentpage',
            name='office_phone',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
