# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-15 02:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('canonical', models.URLField(blank=True, default='')),
                ('title_tag', models.CharField(blank=True, default='', max_length=255)),
                ('meta_title', models.CharField(blank=True, default='', max_length=255)),
                ('meta_description', models.TextField(blank=True, default='')),
                ('meta_keywords', models.TextField(blank=True, default='')),
                ('og_title', models.CharField(blank=True, default='', max_length=255)),
                ('og_type', models.CharField(blank=True, default='', max_length=50)),
                ('og_url', models.URLField(blank=True, default='')),
                ('og_img', models.URLField(blank=True, default='')),
                ('og_description', models.TextField(blank=True, default='')),
                ('twitter_card', models.CharField(blank=True, default='', help_text='Type of Twitter card', max_length=50)),
                ('twitter_site', models.CharField(blank=True, default='', help_text='@name of publisher', max_length=50)),
                ('twitter_title', models.CharField(blank=True, default='', max_length=255)),
                ('twitter_description', models.CharField(blank=True, default='', max_length=200)),
                ('twitter_creator', models.CharField(blank=True, default='', help_text='@name of author', max_length=50)),
                ('twitter_image', models.CharField(blank=True, default='', help_text='Images must be at least 120x120px', max_length=255)),
                ('template_override', models.CharField(blank=True, default='', help_text='Load this specific page template', max_length=255)),
                ('description', wagtail.core.fields.RichTextField(blank=True, default='')),
                ('featured_video_url', models.URLField(blank=True, default='', help_text='Youtube or Vimeo URL to a video about your office')),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='RegionPageGalleryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='suburbs.RegionPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SuburbIndex',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('canonical', models.URLField(blank=True, default='')),
                ('title_tag', models.CharField(blank=True, default='', max_length=255)),
                ('meta_title', models.CharField(blank=True, default='', max_length=255)),
                ('meta_description', models.TextField(blank=True, default='')),
                ('meta_keywords', models.TextField(blank=True, default='')),
                ('og_title', models.CharField(blank=True, default='', max_length=255)),
                ('og_type', models.CharField(blank=True, default='', max_length=50)),
                ('og_url', models.URLField(blank=True, default='')),
                ('og_img', models.URLField(blank=True, default='')),
                ('og_description', models.TextField(blank=True, default='')),
                ('twitter_card', models.CharField(blank=True, default='', help_text='Type of Twitter card', max_length=50)),
                ('twitter_site', models.CharField(blank=True, default='', help_text='@name of publisher', max_length=50)),
                ('twitter_title', models.CharField(blank=True, default='', max_length=255)),
                ('twitter_description', models.CharField(blank=True, default='', max_length=200)),
                ('twitter_creator', models.CharField(blank=True, default='', help_text='@name of author', max_length=50)),
                ('twitter_image', models.CharField(blank=True, default='', help_text='Images must be at least 120x120px', max_length=255)),
                ('template_override', models.CharField(blank=True, default='', help_text='Load this specific page template', max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='SuburbPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('canonical', models.URLField(blank=True, default='')),
                ('title_tag', models.CharField(blank=True, default='', max_length=255)),
                ('meta_title', models.CharField(blank=True, default='', max_length=255)),
                ('meta_description', models.TextField(blank=True, default='')),
                ('meta_keywords', models.TextField(blank=True, default='')),
                ('og_title', models.CharField(blank=True, default='', max_length=255)),
                ('og_type', models.CharField(blank=True, default='', max_length=50)),
                ('og_url', models.URLField(blank=True, default='')),
                ('og_img', models.URLField(blank=True, default='')),
                ('og_description', models.TextField(blank=True, default='')),
                ('twitter_card', models.CharField(blank=True, default='', help_text='Type of Twitter card', max_length=50)),
                ('twitter_site', models.CharField(blank=True, default='', help_text='@name of publisher', max_length=50)),
                ('twitter_title', models.CharField(blank=True, default='', max_length=255)),
                ('twitter_description', models.CharField(blank=True, default='', max_length=200)),
                ('twitter_creator', models.CharField(blank=True, default='', help_text='@name of author', max_length=50)),
                ('twitter_image', models.CharField(blank=True, default='', help_text='Images must be at least 120x120px', max_length=255)),
                ('template_override', models.CharField(blank=True, default='', help_text='Load this specific page template', max_length=255)),
                ('description', wagtail.core.fields.RichTextField(blank=True, default='')),
                ('featured_video_url', models.URLField(blank=True, default='', help_text='Youtube or Vimeo URL to a video about your office')),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='SuburbPageGalleryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='suburbs.SuburbPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
