# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 03:02
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suburbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionpage',
            name='structured_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, help_text='json-ld Structured Data'),
        ),
        migrations.AddField(
            model_name='suburbindex',
            name='structured_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, help_text='json-ld Structured Data'),
        ),
        migrations.AddField(
            model_name='suburbpage',
            name='structured_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, help_text='json-ld Structured Data'),
        ),
    ]
