# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suburbs', '0003_suburbindexfeaturedsuburb'),
    ]

    operations = [
        migrations.AddField(
            model_name='suburbpage',
            name='postcode',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AddField(
            model_name='suburbpage',
            name='state',
            field=models.CharField(blank=True, choices=[('nsw', 'New South Wales'), ('vic', 'Victoria'), ('qld', 'Queensland'), ('act', 'Australian Capital Territory'), ('tas', 'Tasmania'), ('sa', 'South Australia'), ('wa', 'Western Australia'), ('nt', 'Northern Territory')], default='', max_length=10),
        ),
    ]
