# Generated by Django 2.0.3 on 2018-04-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suburbs', '0005_auto_20180405_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suburbpagedwellingstats',
            name='dwelling_type',
            field=models.CharField(max_length=255, verbose_name='Type'),
        ),
    ]
