# Generated by Django 2.0.4 on 2018-04-29 23:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suburbs', '0007_suburbpagesimilarsuburbs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suburbpagedwellingstats',
            name='percentage',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
