# Generated by Django 2.0.4 on 2018-05-08 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('suburbs', '0008_auto_20180429_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='suburbindex',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
