# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-08 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20171207_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='canonical',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='meta_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='meta_keywords',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='meta_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='og_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='og_img',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='og_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='og_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='og_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='twitter_card',
            field=models.CharField(blank=True, default='', help_text='Type of Twitter card', max_length=50),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='twitter_creator',
            field=models.CharField(blank=True, default='', help_text='@name of author', max_length=50),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='twitter_description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='twitter_image',
            field=models.CharField(blank=True, default='', help_text='Images must be at least 120x120px', max_length=255),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='twitter_site',
            field=models.CharField(blank=True, default='', help_text='@name of publisher', max_length=50),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='twitter_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='canonical',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='meta_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='meta_keywords',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='meta_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='og_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='og_img',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='og_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='og_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='og_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='twitter_card',
            field=models.CharField(blank=True, default='', help_text='Type of Twitter card', max_length=50),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='twitter_creator',
            field=models.CharField(blank=True, default='', help_text='@name of author', max_length=50),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='twitter_description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='twitter_image',
            field=models.CharField(blank=True, default='', help_text='Images must be at least 120x120px', max_length=255),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='twitter_site',
            field=models.CharField(blank=True, default='', help_text='@name of publisher', max_length=50),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='twitter_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
