# Generated by Django 2.0.4 on 2018-04-30 01:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formbuilder_filefield', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='canonical',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='formpage',
            name='meta_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='formpage',
            name='meta_keywords',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='formpage',
            name='meta_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='formpage',
            name='og_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='formpage',
            name='og_img',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='formpage',
            name='og_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='formpage',
            name='og_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='formpage',
            name='og_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='formpage',
            name='structured_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, help_text='json-ld Structured Data'),
        ),
        migrations.AddField(
            model_name='formpage',
            name='template_override',
            field=models.CharField(blank=True, default='', help_text='Load this specific page template', max_length=255),
        ),
        migrations.AddField(
            model_name='formpage',
            name='title_tag',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='formpage',
            name='twitter_card',
            field=models.CharField(blank=True, default='', help_text='Type of Twitter card', max_length=50),
        ),
        migrations.AddField(
            model_name='formpage',
            name='twitter_creator',
            field=models.CharField(blank=True, default='', help_text='@name of author', max_length=50),
        ),
        migrations.AddField(
            model_name='formpage',
            name='twitter_description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='formpage',
            name='twitter_image',
            field=models.CharField(blank=True, default='', help_text='Images must be at least 120x120px', max_length=255),
        ),
        migrations.AddField(
            model_name='formpage',
            name='twitter_site',
            field=models.CharField(blank=True, default='', help_text='@name of publisher', max_length=50),
        ),
        migrations.AddField(
            model_name='formpage',
            name='twitter_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
