# Generated by Django 2.0.3 on 2018-03-19 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listingenquiry',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.AlterField(
            model_name='listingenquiry',
            name='sent_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
