# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-04 20:45
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuburbData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('urban_area', models.CharField(blank=True, default='', max_length=50)),
                ('state_code', models.CharField(max_length=3)),
                ('state', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=4)),
                ('type', models.CharField(max_length=25)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('elevation', models.IntegerField()),
                ('population', models.IntegerField()),
                ('area', models.DecimalField(decimal_places=3, max_digits=8)),
                ('local_government_area', models.CharField(max_length=50)),
                ('timezone', models.CharField(max_length=50)),
                ('bordering_locations', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
        ),
    ]
