# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-05 08:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suburbs_database', '0003_auto_20180205_0809'),
        ('suburbs_database', '0003_auto_20180205_0435'),
    ]

    operations = [
    ]
