# Generated by Django 2.0.3 on 2018-03-18 23:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descriptive_name', models.CharField(default='Property Alert', max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('criteria', django.contrib.postgres.fields.jsonb.JSONField()),
                ('frequency', models.IntegerField(choices=[(1, 'Daily'), (7, 'Weekly'), (30, 'Monthly')], default=7)),
                ('last_sent', models.DateTimeField(blank=True, default=None, null=True)),
                ('unsubscribed', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            managers=[
                ('subscribers', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PropertyAlertLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', models.DateTimeField(auto_now_add=True)),
                ('listings', models.IntegerField(default=0)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.PropertyAlert')),
            ],
        ),
    ]
