# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-08 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0002_agentpage_source_id'),
        ('wagtailimages', '0019_delete_filter'),
        ('realestate', '0002_auto_20180108_0342'),
        ('offices', '0002_officepage_source_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial_type', models.CharField(blank=True, choices=[('Sale', 'Sale'), ('Rental', 'Rental'), ('Commercial', 'Commercial')], default='', max_length=10)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('headline', models.CharField(blank=True, default='', max_length=150)),
                ('comments', models.CharField(blank=True, default='', max_length=1500)),
                ('date', models.DateField(blank=True, default=None, null=True)),
                ('agents', models.ManyToManyField(blank=True, related_name='testimonials', to='agents.AgentPage')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('listing', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='realestate.PropertyListing')),
                ('offices', models.ManyToManyField(blank=True, related_name='testimonials', to='offices.OfficePage')),
            ],
        ),
    ]
