# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-08 03:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agentpage_source_id'),
        ('offices', '0002_officepage_source_id'),
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.AgentPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestimonialOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offices.OfficePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='agents',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='offices',
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='comments',
            field=wagtail.core.fields.RichTextField(blank=True, default='', max_length=1500),
        ),
        migrations.AddField(
            model_name='testimonialoffice',
            name='testimonial',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='testimonials.Testimonial'),
        ),
        migrations.AddField(
            model_name='testimonialagent',
            name='testimonial',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='testimonials.Testimonial'),
        ),
    ]
