# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-01 21:30
from __future__ import unicode_literals

from django.db import migrations, models
from django.template.defaultfilters import slugify
from django.utils.crypto import get_random_string


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0004_auto_20180201_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='canonical',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='og_description',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='og_img',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='og_title',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='og_type',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='og_url',
        ),
        # migrations.RemoveField(
        #     model_name='testimonial',
        #     name='page_ptr',
        # ),
        migrations.RemoveField(
            model_name='testimonial',
            name='template_override',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='title_tag',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='twitter_card',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='twitter_creator',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='twitter_description',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='twitter_image',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='twitter_site',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='twitter_title',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonial',
            name='slug',
            field=models.SlugField(default=get_random_string, help_text='URL Slug for display page. Must be unique.'),
            preserve_default=False,
        ),
    ]
