# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-08 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0006_auto_20180207_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='video_url',
            field=models.URLField(blank=True, default='', help_text='Vimeo or Youtube embed URL'),
        ),
    ]
