# Generated by Django 2.0.3 on 2018-03-19 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0007_testimonial_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='listing',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='realestate.PropertyListing'),
        ),
    ]
